### ISSUE TITLE
ppx_js_style is enforced

### ISSUE THREAD

**Issue by ivg** [janestreet/ppx_js_style#1]
The problem is that `ppx_js_style` is a hard dependency of `ppx_base` which is a dependency of many (if not all) ppx-based rewriters. As a result it enforces all the deprecation messages to contain a date of deprecation. This requirement may have some meaning in the Janestreet release cycle, but really doesn't make any sense if you're using semantic versioning or actually any versioning.

**Comment by yminsky** [comment]
Being a dependency of Base merely means that you have to install it, not that you have to turn it on, no?

**Comment by ivg** [comment]
Well, I'm not running it actually, at least I didn't do anything specific to run it, so I believe that the check is enabled by default. I've tried the `-no-check` option of `ppx-jane` but it didn't help. There are also some options that enables/disables type annotations checks and docstrings, but I didn't find anything that deals with the deprecation warning.

**Comment by yminsky** [comment]
Ah, so does this mean you've enabled ppx_jane? You don't need to do that to
use base; you can just pick and choose amongst the syntax extensions you
want.

That said, I can see why you'd want something like ppx_jane with that check
omitted. Is that what you're looking for?

**Comment by trefis** [comment]
`-no-check` is unrelated to `ppx_js_style`, it is here to disable the checks which are built in `ppx_driver` (e.g. checking that no attributes was silently dropped, that kind of things).

I think it makes sense, outside our walls, to remove `ppx_js_style` from `ppx_jane`.
I'll do that the next I push to github.

**Comment by ivg** [comment]
> That said, I can see why you'd want something like ppx_jane with that check
omitted. Is that what you're looking for?

Yep.

**Comment by trefis** [comment]
I made the check optional (and off by default) in cc52570bfbeebcb6da1b056b55fdc2b8960e82c6 .
`ppx_js_style` is still part of `ppx_jane` though (and we actually want to keep it that way to compile our packages)
